### ISSUE TITLE
Implement onClick logic to `<RecyclerView />` list items

### ISSUE THREAD

**Issue by jacobburgo** [theRedAces/life_is_well#52]
### Is your feature request related to a problem? Please describe.
Button need good clicky.

### Describe the solution you'd like
Implement onClick logic. Needs to depend on something to distinguish between an always changing dynamic list of buttons and then set the listener.
EDIT: Would need to set custom ids using numbers, save that number to the goalItem itself for later access. Also need to look into dynamically creating a layout using those IDs. I will make a separate issue for that.
OR
I can potentially can fill the array to a point with good data, then after, let's say 3 items in the list, everything else gets the same default generic values and set `item.visibility = View.GONE`. From this point, instead of trying to `invalidate()` the screen (Which I have not given up on) you can just set the 3 values in the `onClickListener()` and then set `item.visibility = view.VISIBLE`. After that we would also need to keep track of the index of the `goalList`, because after `index = 5` we would need to start scrolling down the page. This would require control of the top level parent's `scrollHeight`, something I'm not sure can even be done in Kotlin/Android Studio. But if so, determine `scrollHeight` from some kind of function that gets the height of an item at a position, gets the height of the screen (since it can be different per phone, but I think `dp` instead of `px` makes this point void, but idk), then accounts for any margin/padding, and finally sets that to the scroll height.

### Additional context

Obviously the former of the options is much better for an untold number of reasons, but getting functioning things is my top priority for this class. Noting that should never be a top priority ever again while a developer.

**Comment by MillerShane** [comment]
Solved issue
